#!/bin/sh

DEBUG=false
SNMPID=false
SNMPID=true

while echo $1 |grep "^-" >/dev/null
do
  case $1 in
    "--snmp" )
      SNMPID=true
      shift
      ;;
    "--debug" )
      DEBUG=true
      shift
      ;;
    "--help" | "-?" | "-h" | * )
      echo Usage:
      echo $0 "[OPTIONS] "
      echo OPTIONS:
      echo "--help -? -h"
      echo "--snmp ;# attempt to identify the device via snmp"
      exit
      ;;
  esac
done

ADDRESS=$1

if [ -z $ADDRESS ]
then
  #echo Usage:
  #echo $0 "<IP-ADDRESS>"
  ADDRESS="192.168.1.100"
fi

#. ./softtab.sh

CWSysDescr=".1.3.6.1.4.1.9.9.25.1.1.1.2.7"
sysObjectID=".1.3.6.1.2.1.1.2"
busyPer="1.3.6.1.4.1.9.2.1.56"
avgBusy1="1.3.6.1.4.1.9.2.1.57"
avgBusy5="1.3.6.1.4.1.9.2.1.58"

OID=$avgBusy5


$DEBUG && echo 'ping -w3 -c3 $ADDRESS'
if ping -w2 -c2 $ADDRESS >/dev/null
then
  if false ;# echo $ADDRESS |fgrep -e ".100." -e ".48.49." >/dev/null
  then
    SNMPID=true
  fi
  if $SNMPID
  then
    for OID in $busyPer $avgBusy1 $avgBusy5
    do
    if $DEBUG
    then
      echo 'snmpwalk -On -c public -v2c -Pe -m "" $ADDRESS $OID '
      echo 'snmpwalk -On -c public -v2c -Pe -m ""' $ADDRESS $OID
      SNMPRESULT=`snmpwalk -On -c public -v2c -Pe -m "" $ADDRESS $OID |sed 's/^[^:]*: //'`
    else
      SNMPRESULT=`snmpwalk -On -c public -v2c -Pe -m "" $ADDRESS $OID 2>/dev/null|sed 's/^[^:]*: //'`
    fi
    SNMPSYSTEM="$SNMPSYSTEM $SNMPRESULT"
    done
    echo $ADDRESS SWITCHRESPONDING $SNMPSYSTEM
  else
    echo $ADDRESS RESPONDING
  fi
else
  echo $ADDRESS NOT RESPONDING
fi
