#!/bin/sh

# ifStackTable 1.3.6.1.2.1.31.1.2
#  ifStackEntry 1.3.6.1.2.1.31.1.2.1
#   ifStackStatus 1.3.6.1.2.1.31.1.2.1.3
ifStackStatus="1.3.6.1.2.1.31.1.2.1.3"
#ifStackStatus maps Interface_Index+subInterface_Index to subInterface_Status

while echo $1 |grep "^-" >/dev/null
do
  case $1 in

    "--switch" )
      SWITCH="$1"
      shift;shift
      ;;

    "--debug" )
      DEBUG="true"
      shift
      ;;

    "--help" | "-?" | "-h" | * )
      echo Usage:
      echo $0 "[OPTIONS] <SUBNET> <STARTOCTET> <ENDOCTET>"
      echo OPTIONS:
      echo "--help -? -h"
      echo "--debug         ;# show debugging info"
      echo "--switch        ;# specify a switch to query"
      exit
      ;;
  esac
done

IFINDEX=$1

DEBUG=${DEBUG:-"false"}
SWITCH=${SWITCH:-"192.168.1.254"}
QueryDevice=$SWITCH

if [ "${IFINDEX}x" != "x" ]
then

  OID=${ifStackStatus}.${IFINDEX}
  OUTPUT=`
  $DEBUG && echo "snmpwalk -On -c public -v2c -Pe -m "'""'" $QueryDevice $OID" >&2
  snmpwalk -On -c public -v2c -Pe -m "" $QueryDevice $OID \
  | sed -e 's/^\.'"$OID"'\.//' \
  | if true
    then
      sed -e 's/= INTEGER: .*$//'
    else
      sed -e 's/Hex-STRING: \(..\) \(..\) \(..\) \(..\) \(..\) \(..\) *$/\1\2.\3\4.\5\6/'
    fi`
else
  OID=${ifStackStatus}
  $DEBUG && echo "snmpwalk -On -c public -v2c -Pe -m "'""'" $QueryDevice $OID" >&2
  snmpwalk -On -c public -v2c -Pe -m "" $QueryDevice $OID \
  | fgrep -v ${OID}.0. \
  | grep -v "${OID}\.[^ .]*\.0" \
  | sed -e 's/^\.'"$OID"'\.//' \
  | if true
    then
      sed -e 's/Hex-STRING: *//'
    else
      sed -e 's/Hex-STRING: \(..\) \(..\) \(..\) \(..\) \(..\) \(..\) *$/\1\2.\3\4.\5\6/'
    fi

fi

echo $OUTPUT

exit
####################################################


#snmpwalk -c public -v2c -Pe -m ./mibs/CISCO-SMI.my:./mibs/CISCO-STACK-MIB.my 192.168.1.254 .1.3.6.1.2.1.3.1.1.1
ifDescr=".1.3.6.1.2.1.2.2.1.2"
#ifDescr maps Interface_Index to VLAN_Number
OID=$ifDescr
snmpwalk -On -c public -v2c -Pe -m "" $QueryDevice $OID \
|sed -e 's/^'"${ifDescr}."'//' -e 's/ = [^"]*"/ /' -e 's/"[^"]*$//'
#|sed -e 's/^'"$ifDescr"//" -e 's/^[^"]*"//' -e 's/"[^"]*$//'

atIfIndex=".1.3.6.1.2.1.3.1.1.1"
# RFC1213-MIB::atIfIndex maps Interface_Index+IP_Address to Interface_Index
# OID=$atIfIndex

#atPhysAddress=".1.3.6.1.2.1.3.1.1.2"
#atPhysAddress maps Interface_Index+IP_address to MAC_Address
#OID=$atPhysAddress


#snmpwalk -c public -v2c -Pe -m ""  $QueryDevice $OID
#snmpwalk -c public -v2c -Pe $QueryDevice $OID
#snmpwalk -On -c public -v2c -Pe  $QueryDevice $OID
snmpwalk -On -c public -v2c -Pe -m "" $QueryDevice $OID
